# Base image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy necessary files
# Copy necessary files
COPY src/best_run_id.txt .
COPY src/app.py .
COPY src/mlruns ./mlruns


# Install dependencies
RUN pip install --no-cache-dir mlflow scikit-learn pandas fastapi uvicorn pydantic

# Set MLflow tracking to local folder
ENV MLFLOW_TRACKING_URI=file:./mlruns

# Expose port for FastAPI
EXPOSE 8000

# Run the FastAPI app
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]

