# Use lightweight Python image
FROM python:3.11-slim

# Maintainer info
LABEL maintainer="chloe"

# Set working directory
WORKDIR /app

# Copy prediction script and saved model
COPY auto_selection.py .
COPY mlruns/ mlruns/

# Install only the needed libraries
RUN pip install --no-cache-dir mlflow scikit-learn pandas

# Set MLflow to local
ENV MLFLOW_TRACKING_URI=file:./mlruns

# Run the prediction script
CMD ["python", "auto_selection.py"]
