FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Install Poetry
RUN pip install --no-cache-dir poetry

# Configure Poetry
RUN poetry config virtualenvs.create false

# Copy dependency files
COPY pyproject.toml poetry.lock ./

# Install dependencies
RUN pip install --no-cache-dir mlflow scikit-learn pandas fastapi uvicorn pydantic catboost


# Copy source code
COPY src/app.py ./app.py
COPY src/mlruns ./mlruns
COPY best_run_id.txt ./best_run_id.txt

# Set environment variables
ENV PYTHONPATH=/app

# Expose port
EXPOSE 8000

# Start server
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
